### ISSUE TITLE
Pub.dev

### ISSUE THREAD

**Issue by grizzly** [jinyus/flutter_android_battery_optimization#1]
Will it be available on pub.dev?

**Comment by zupat** [comment]
I would but I don't want to make my email address public. You can still import the package using:

```yaml
android_battery_optimization:
    git:
      url: https://github.com/jinyus/flutter_android_battery_optimization.git
```
